# Generated by Django 3.2.4 on 2021-06-21 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_auto_20210621_0815'),
        ('search', '0003_alter_search_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.location'),
        ),
    ]
