# Generated by Django 3.2.4 on 2021-06-15 11:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='My_Jobs',
            new_name='MyApplications',
        ),
    ]
