# Generated by Django 3.2.4 on 2021-06-15 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_rename_my_jobs_myapplications'),
    ]

    operations = [
        migrations.RenameField(
            model_name='updates',
            old_name='job',
            new_name='application',
        ),
    ]
