# Generated by Django 3.2.4 on 2021-06-16 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_rename_job_updates_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
