# Generated by Django 3.2.4 on 2021-06-17 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_alter_myapplications_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myapplications',
            name='status',
            field=models.CharField(choices=[('INTERTESTED', 'intertested'), ('APPLIED', 'applied'), ('INTERVIEW', 'interview'), ('ACCEPTED', 'accepted'), ('REJECTED', 'rejected')], default='INTERTESTED', max_length=200),
        ),
    ]
