# Generated by Django 3.2.4 on 2021-06-20 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_auto_20210620_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblisting',
            name='description',
            field=models.CharField(max_length=2000, unique=True),
        ),
    ]
