# Generated by Django 3.2.4 on 2021-06-27 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0012_auto_20210621_0847'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='joblisting',
            options={'ordering': ['-created']},
        ),
    ]
